import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SignUp from "./Components/Sign-up/page";
import Navbar from "./Components/Navbar/page";
import Brands from "./Components/Brands/page";
import Arrivals from "./Components/Arrivals/page";
import Selling from "./Components/Selling/page";
import Dress from "./Components/Dress/page";
import Customers from "./Components/Customers/page";
import Footer from "./Components/Footer/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SignUp/>
        <Navbar/>
        {children}
        <Brands/>
        <Arrivals/>
        <Selling/>
        <Dress/>
        <Customers/>
        <Footer/>
      </body>
    </html>
  );
}
